# Generated by Django 4.1.2 on 2022-10-19 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advocate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='advocate/pics')),
                ('short_bio', models.CharField(max_length=200)),
                ('long_bio', models.TextField()),
                ('advocate_years_experience', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.URLField()),
                ('twitter', models.URLField()),
                ('github', models.URLField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advocate.advocate')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company/logo')),
                ('summary', models.CharField(max_length=200)),
                ('href', models.URLField()),
                ('advocate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advocate.advocate')),
            ],
        ),
    ]
