# Generated by Django 4.1.2 on 2022-10-19 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='advocate',
        ),
        migrations.RemoveField(
            model_name='links',
            name='advocate',
        ),
        migrations.AddField(
            model_name='advocate',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate.company'),
        ),
        migrations.AddField(
            model_name='advocate',
            name='links',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate.links'),
        ),
    ]
