# Generated by Django 4.1.2 on 2022-10-19 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0003_company_advocates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='advocates',
        ),
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='company/logo')),
                ('summary', models.CharField(max_length=200)),
                ('href', models.URLField()),
                ('advocates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate.advocate')),
            ],
        ),
    ]
