# Generated by Django 4.1.2 on 2022-10-19 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0004_remove_company_advocates_companies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companies',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Company'},
        ),
        migrations.AlterModelOptions(
            name='links',
            options={'verbose_name_plural': 'Links'},
        ),
        migrations.RemoveField(
            model_name='companies',
            name='href',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='summary',
        ),
        migrations.AddField(
            model_name='companies',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate.company'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='advocates',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='advocate.advocate'),
        ),
    ]
