# Generated by Django 4.1.2 on 2022-10-19 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0005_alter_companies_options_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='href',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='logo',
            field=models.ImageField(null=True, upload_to='company/logo'),
        ),
        migrations.AddField(
            model_name='companies',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='companies',
            name='summary',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
