# Generated by Django 4.1.2 on 2022-10-21 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0007_remove_companies_company_remove_companies_advocates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='advocates',
            field=models.ManyToManyField(to='advocate.advocate'),
        ),
    ]
