# Generated by Django 4.1.2 on 2022-10-21 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0008_alter_companies_advocates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='href',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='name',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='summary',
        ),
        migrations.AddField(
            model_name='companies',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='advocate.company'),
            preserve_default=False,
        ),
    ]
