# Generated by Django 4.1.2 on 2022-10-21 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advocate', '0009_remove_companies_href_remove_companies_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='advocate.company'),
        ),
    ]
